from decouple import config

ENTOUREO_EMAIL = config('ENTOUREO_EMAIL')
ENTOUREO_PASSWORD = config('ENTOUREO_PASSWORD')
HUGGINGCHAT_USERNAME = config('HUGGINGCHAT_USERNAME')
HUGGINGCHAT_PASSWORD = config('HUGGINGCHAT_PASSWORD')
